backend/urls.py
# myapp/urls.py
from django.urls import path
from .views import login_view, sign_up, update_user, neighbourhood,homeProfile, findfriend, filter_friend, send_friend_request, blinkboard, delete_friend

app_name = 'backend'

urlpatterns = [
    path('', login_view, name='login'),
    path('login/', login_view, name='login'),
    path('sign-up/', sign_up, name='signup'),
    path('update/', update_user, name='update'),
    path('homeProfile/', homeProfile, name='home'),
    path('neighbourhood/', neighbourhood, name='neighbourhood'),
    path('findfriend/', findfriend, name='findfriend'),
    path('blinkboard/', blinkboard, name='blinkboard'),
    path('filterfriend/', filter_friend, name='filterfriend'),
    path('send-request/', send_friend_request, name='send_friend_request'),
    path('delete-friend/', delete_friend, name='delete_friend'),
]

blinkboard/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('backend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/views.py
import datetime
import json
import time
import uuid

from django.contrib.auth import authenticate, login
from django.forms import model_to_dict
from django.http import HttpResponseBadRequest, JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken, AccessToken

from .models import User, Friends

import json
from datetime import datetime


class CustomJSONEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.isoformat()
        return super().default(obj)


def get_user_attribute(user, friend, attribute):
    return getattr(friend.from_user if friend.from_user != user else friend.to_user, attribute)


def get_all_friends(user):
    # Retrieve friends where the user is the sender (from_user) and the request is accepted
    sent_and_accepted = Friends.objects.filter(from_user=user, status='Accepted')

    # Retrieve friends where the user is the receiver (to_user) and the request is accepted
    received_and_accepted = Friends.objects.filter(to_user=user, status='Accepted')
    # Combine both sets of friends
    all_friends = sent_and_accepted | received_and_accepted

    return all_friends


def get_friends(user):
    # Retrieve friends where the user is the sender (from_user) and the request is accepted
    sent_and_accepted = Friends.objects.filter(from_user=user)

    # Retrieve friends where the user is the receiver (to_user) and the request is accepted
    received_and_accepted = Friends.objects.filter(to_user=user)

    # Combine both sets of friends
    all_friends = sent_and_accepted | received_and_accepted

    return all_friends


@csrf_exempt
@api_view(['POST', 'GET'])
@permission_classes([AllowAny])
def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    elif request.method == 'POST':
        username = request.data.get('username')
        password = request.data.get('password')
        try:
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                refresh = RefreshToken.for_user(user)
                access_token = str(refresh.access_token)
                refresh_token = str(refresh)

                context = {
                    'user': {
                        'id': user.id,
                        'username': user.username,
                        'email': user.email,
                        'location': user.location,
                        'bio': user.bio,
                        'quote': user.quote,
                        'avatar': user.avatar if user.avatar else None,
                        'blink_board': user.blink_board,
                        'blink_board_image': user.blink_board_image,
                        'updated_at': user.updated_at

                    },
                    'access_token': access_token,
                }

                # return Response(context)
                # session_id = str(user.id)

                # Render the desired template, for example 'homeProfile.html'
                response = render(request, 'homeProfile.html', context)
                # response.set_cookie('access_token', access_token)
                response.set_cookie('access_token', access_token)
                response.set_cookie(f'user_id_{user.id}', user.id)

                return response
            else:
                return render(request, 'loginFailed.html')
        except:
            return render(request, 'loginFailed.html')


@api_view(['POST', 'GET'])
@permission_classes([AllowAny])
def sign_up(request):
    if request.method == 'GET':
        return render(request, 'signup.html')

    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        if User.objects.filter(email=email).exists():
            return render(request, 'signupfailed.html')

        if User.objects.filter(username=username).exists():
            return render(request, 'signupfailed.html')
        User.objects.create_user(email=email, username=username, password=password)
        return render(request, 'NewUserLogin.html')


@api_view(['POST', 'GET'])
@permission_classes([IsAuthenticated])
def update_user(request):
    # if request.method == 'GET':
    #     try:
    #         user = request.user
    #         return render(request, 'homeProfile.html', {'user': user})
    #     except Exception as e:
    #         return render(request, 'login.html')

    if request.method == 'POST':
        try:
            user = request.user
            if user.is_authenticated:
                location = request.data.get("location", None)

                bio = request.data.get("bio", None)
                quote = request.data.get("quote", None)
                if location and len(location) > 0:
                    user.location = location

                if bio and len(bio) > 0:
                    user.bio = bio
                if quote and len(quote) > 0:
                    user.quote = quote

                avatar_file = request.FILES.get('avatar')
                if avatar_file:
                    if avatar_file.size > 0:
                        user.avatar.save(avatar_file.name, avatar_file, save=True)
                    else:
                        print("Uploaded file is empty.")

                blink_board = request.data.get('blink_board', None)
                if blink_board and len(blink_board) > 0:
                    user.blink_board = blink_board
                    user.updated_at = datetime.now()

                avatar_file = request.FILES.get('blink_board_image')
                if avatar_file:
                    if avatar_file.size > 0:
                        user.blink_board_image.save(avatar_file.name, avatar_file, save=True)
                    else:
                        print("Uploaded file is empty.")
                user.save()
                user = model_to_dict(user)
                return JsonResponse({'user': user, 'success': True})
                # return render(request, 'homeProfile.html', context={'user': user})
            else:
                print("User not authenticated!")
                return JsonResponse({'success': False, 'error': 'User not authenticated'}, status=401)
        except Exception as e:
            return render(request, 'login.html')


def get_neighbourhood_context(user):
    pending_request = Friends.objects.filter(to_user=user, status='Pending')
    # accepted_request = get_all_friends(user)
    sent_and_accepted = Friends.objects.filter(from_user=user, status='Accepted')

    # Retrieve friends where the user is the receiver (to_user) and the request is accepted
    received_and_accepted = Friends.objects.filter(to_user=user, status='Accepted')

    neighbour_list = [{'username': neighbour.to_user.username,
                       'avatar': neighbour.to_user.avatar.url if neighbour.to_user.avatar else None,
                       'blink_board': neighbour.to_user.blink_board,
                       'blink_board_image': neighbour.to_user.blink_board_image.url if neighbour.to_user.blink_board_image else None,
                       'updated_at': neighbour.to_user.updated_at,
                       'location': neighbour.to_user.location if neighbour.to_user.location else "",
                       'bio': neighbour.to_user.bio if neighbour.to_user.bio else "",
                       'quote': neighbour.to_user.quote if neighbour.to_user.quote else ""} for neighbour in
                      sent_and_accepted]

    neighbour_list.extend([{'username': neighbour.from_user.username,
                            'avatar': neighbour.from_user.avatar.url if neighbour.from_user.avatar else None,
                            'blink_board': neighbour.from_user.blink_board,
                            'blink_board_image': neighbour.from_user.blink_board_image.url if neighbour.from_user.blink_board_image else None,
                            'updated_at': neighbour.from_user.updated_at,
                            'location': neighbour.from_user.location if neighbour.from_user.location else "",
                            'bio': neighbour.from_user.bio if neighbour.from_user.bio else "",
                            'quote': neighbour.from_user.quote if neighbour.from_user.quote else ""} for neighbour in
                           received_and_accepted])

    pending_list = [{'username': neighbour.from_user.username,
                     'avatar': neighbour.from_user.avatar.url if neighbour.from_user.avatar else None,
                     'blink_board': neighbour.from_user.blink_board,
                     'blink_board_image': neighbour.from_user.blink_board_image.url if neighbour.from_user.blink_board_image else None,
                     'updated_at': neighbour.from_user.updated_at} for neighbour in
                    pending_request]

    context = {
        'accepted_neighbourhoods': neighbour_list,
        'pending_neighbourhoods': pending_list,
        'neighbours': json.dumps(neighbour_list, cls=CustomJSONEncoder)
    }
    return context


@api_view(['POST', 'GET'])
@permission_classes([AllowAny])
def neighbourhood(request):
    if request.method == 'GET':
        try:
            access_token = request.GET.get('access_token')
            # decoded_token = AccessToken(access_token)

            user = User.objects.filter(id=access_token).first()
            context = get_neighbourhood_context(user)
            context['user'] = user

backend/templates/NewUserLogin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | BlinkBoard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Add Custom Style CSS -->
    <link rel="stylesheet" href="{% static 'backend/style.css' %}">
    <style>
        .Alert-container{
        border: 1px solid #076116;
        border-radius: 3px;
        text-align:center;
        background-color: #00ff9945;
        }
    </style>
</head>
<body>
    <section class="bb-main--body">
        <div class="bb--screen-block login--screen" style="margin-top: 30vh; border:none;">
            <div class="bb-login-screen-container">
                <div class="bb-form-wrapper">
                    <div class="bb-loginform__wrapper mx-auto">
                        <div class="bb-loginform__inner">
                            <div class="bb-loginform__logo-wrapper py-3 mb-3">
                                <img src="{% static 'backend/logo.jpg' %}" alt="" class="bb-logo img-fluid">
                            </div>
                            <div class="bb-loginform__wrapper">
                                <form  method="post" action="{% url 'backend:login' %}" id="login-form" class="bb__login-form mx-auto">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="login__username" placeholder="Username" name="username">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="login__password" placeholder="Password" name="password">
                                    </div>
                                    <div class="form-group Alert-container">
                                        <p style="padding: 0.375rem 0.75rem; margin-bottom:0px;">New User Registered</p>
                                    </div>
                                    <button type="submit" class="btn btn-success btn-block bb-form__btn" id="login__submit">Login</button>
                                    <div class="form__alert alert fz-16 text-center" role="alert"></div>
                                </form>
                                <p class="mt-3 text-center fz-16">
                                    Not a member yet? <a href="{% url 'backend:signup' %}" class="bb-form__switcher">Signup here</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Add Bootstrap JS -->
<!--    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js" integrity="sha384-ZVPiMxFg9P5gi7SOKVUv7aSbFSSt7/9XwHHg/jq4x7EJvFZ3xzfp++2QvMZ7GM3L" crossorigin="anonymous"></script>-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-Jjw8f+cdVhqhxDbzmgYKl0WbDq5blXhXu8jScqSAIn0uE9qb9BZZVdAgoasjKwn0" crossorigin="anonymous"></script>
    <!-- Add Custom JavaScript for AJAX -->
<!--    <script type="text/javascript" src="{% static 'backend/js/login.js' %}"></script>-->
</body>
</html>

backend/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | BlinkBoard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Add Custom Style CSS -->
    <link rel="stylesheet" href="{% static 'backend/style.css' %}">
</head>
<body>
    <section class="bb-main--body">
        <div class="bb--screen-block login--screen" style="margin-top: 30vh; border:none;">
            <div class="bb-login-screen-container">
                <div class="bb-form-wrapper">
                    <div class="bb-loginform__wrapper mx-auto">
                        <div class="bb-loginform__inner">
                            <div class="bb-loginform__logo-wrapper py-3 mb-3">
                                <img src="{% static 'backend/logo.jpg' %}" alt="" class="bb-logo img-fluid">
                            </div>
                            <div class="bb-loginform__wrapper">
                                <form  method="post" action="{% url 'backend:login' %}" id="login-form" class="bb__login-form mx-auto">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="login__username" placeholder="Username" name="username">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="login__password" placeholder="Password" name="password">
                                    </div>
                                    <button type="submit" class="btn btn-success btn-block bb-form__btn" id="login__submit">Login</button>
                                    <div class="form__alert alert fz-16 text-center" role="alert"></div>
                                </form>
                                <p class="mt-3 text-center fz-16">
                                    Not a member yet? <a href="{% url 'backend:signup' %}" class="bb-form__switcher">Signup here</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Add Bootstrap JS -->
<!--    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js" integrity="sha384-ZVPiMxFg9P5gi7SOKVUv7aSbFSSt7/9XwHHg/jq4x7EJvFZ3xzfp++2QvMZ7GM3L" crossorigin="anonymous"></script>-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-Jjw8f+cdVhqhxDbzmgYKl0WbDq5blXhXu8jScqSAIn0uE9qb9BZZVdAgoasjKwn0" crossorigin="anonymous"></script>
    <!-- Add Custom JavaScript for AJAX -->
<!--    <script type="text/javascript" src="{% static 'backend/js/login.js' %}"></script>-->
</body>
</html>

backend/templates/loginFailed.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login | BlinkBoard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Add Custom Style CSS -->
    <link rel="stylesheet" href="{% static 'backend/style.css' %}">
    <style>
        .Alert-container{
        border: 1px solid red;
        border-radius: 3px;
        text-align:center;
        background-color: #f001011f;
        }
    </style>
</head>
<body>
    <section class="bb-main--body">
        <div class="bb--screen-block login--screen" style="margin-top: 30vh; border:none;">
            <div class="bb-login-screen-container">
                <div class="bb-form-wrapper">
                    <div class="bb-loginform__wrapper mx-auto">
                        <div class="bb-loginform__inner">
                            <div class="bb-loginform__logo-wrapper py-3 mb-3">
                                <img src="{% static 'backend/logo.jpg' %}" alt="" class="bb-logo img-fluid">
                            </div>
                            <div class="bb-loginform__wrapper">
                                <form  method="post" action="{% url 'backend:login' %}" id="login-form" class="bb__login-form mx-auto">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="login__username" placeholder="Username" name="username">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="login__password" placeholder="Password" name="password">
                                    </div>
                                    <div class="form-group Alert-container">
                                        <p style="padding: 0.375rem 0.75rem; margin-bottom:0px;">Login Failed</p>
                                    </div>
                                    <button type="submit" class="btn btn-success btn-block bb-form__btn" id="login__submit">Login</button>
                                    <div class="form__alert alert fz-16 text-center" role="alert"></div>
                                </form>
                                <p class="mt-3 text-center fz-16">
                                    Not a member yet? <a href="{% url 'backend:signup' %}" class="bb-form__switcher">Signup here</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Add Bootstrap JS -->
<!--    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js" integrity="sha384-ZVPiMxFg9P5gi7SOKVUv7aSbFSSt7/9XwHHg/jq4x7EJvFZ3xzfp++2QvMZ7GM3L" crossorigin="anonymous"></script>-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-Jjw8f+cdVhqhxDbzmgYKl0WbDq5blXhXu8jScqSAIn0uE9qb9BZZVdAgoasjKwn0" crossorigin="anonymous"></script>
    <!-- Add Custom JavaScript for AJAX -->
<!--    <script type="text/javascript" src="{% static 'backend/js/login.js' %}"></script>-->
</body>
</html>

backend/templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login|-BlinkBoard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Add Custom Style CSS -->
    <link
      rel="stylesheet"
      href="{% static 'backend/style.css' %}"
    />

  </head>
  <body>
    <section class="bb-main--body">
      {% csrf_token %}
      <div class="bb--screen-block signup--screen" style="margin-top: 30vh; border:none;">
        <div class="bb-signup-screen-container">
          <div class="bb-form-wrapper">
            <div class="bb-signupform__wrapper mx-auto">
              <div class="bb-signupform__inner">
                <div class="bb-signupform__logo-wrapper py-3 mb-3">
                  <img
                    src="{% static 'backend/logo.jpg' %}"
                    alt=""
                    class="bb-logo img-fluid"
                  />
                </div>
                <div class="bb-signupform__wrapper">
                  <form method="post" action="{% url 'backend:signup' %}" class="bb__signup-form mx-auto">
                    {% csrf_token %}
                    <div class="form-group">
                      <input
                        type="text"
                        class="form-control"
                        id="signup__username"
                        maxlength="16"
                        pattern="[A-Za-z0-9]+"
                        placeholder="Username"
                        name="username"
                      />
                    </div>
                    <!-- Password Input -->
                    <div class="form-group">
                      <input
                        type="password"
                        class="form-control"
                        id="signup__password"
                        maxlength="16"
                        placeholder="Password"
                        name="password"
                      />
                    </div>
                    <!-- Email Input -->
                    <div class="form-group">
                      <input
                        type="email"
                        class="form-control"
                        id="signup__email"
                        placeholder="Email"
                        name="email"
                      />
                    </div>
                    <!-- signup Button -->
                    <button type="submit" class="btn btn-success btn-block bb-form__btn" id="signup__submit">
                      Signup
                    </button>
                    <div class="form__alert alert alert-danger mt-3 fz-16 text-center" style="display:none;" role="alert">
                       This account already exists,please login
                      </div>
                  </form>
                  <!-- Registration Message -->

                  <p class="mt-3 text-center fz-16">
                    Already have an account? <a href="{% url 'backend:login' %}" class="bb-form__switcher">Login here</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Add Bootstrap JS and jQuery -->
<!--    <script src="../Assets/includes/js/jquery.js"></script>-->
    <!-- custom script here -->
<!--    <script src="../Assets/includes/js/formscript.js"></script>-->
  </body>
</html>

backend/templates/signupfailed.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login|-BlinkBoard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Add Custom Style CSS -->
    <link
      rel="stylesheet"
      href="{% static 'backend/style.css' %}"
    />

  </head>
  <body>
    <section class="bb-main--body">
      {% csrf_token %}
      <div class="bb--screen-block signup--screen" style="margin-top: 30vh; border:none;">
        <div class="bb-signup-screen-container">
          <div class="bb-form-wrapper">
            <div class="bb-signupform__wrapper mx-auto">
              <div class="bb-signupform__inner">
                <div class="bb-signupform__logo-wrapper py-3 mb-3">
                  <img
                    src="{% static 'backend/logo.jpg' %}"
                    alt=""
                    class="bb-logo img-fluid"
                  />
                </div>
                <div class="bb-signupform__wrapper">
                  <form method="post" action="{% url 'backend:signup' %}" class="bb__signup-form mx-auto">
                    {% csrf_token %}
                    <div class="form-group">
                      <input
                        type="text"
                        class="form-control"
                        id="signup__username"
                        maxlength="16"
                        pattern="[A-Za-z0-9]+"
                        placeholder="Username"
                        name="username"
                      />
                    </div>
                    <!-- Password Input -->
                    <div class="form-group">
                      <input
                        type="password"
                        class="form-control"
                        id="signup__password"
                        maxlength="16"
                        placeholder="Password"
                        name="password"
                      />
                    </div>
                    <!-- Email Input -->
                    <div class="form-group">
                      <input
                        type="email"
                        class="form-control"
                        id="signup__email"
                        placeholder="Email"
                        name="email"
                      />
                    </div>
                    <div class="form__alert alert alert-danger mt-3 fz-16 text-center">
                                        <p style="padding: 0.375rem 0.75rem; margin-bottom:0px;">Account Already Exists</p>
                                    </div>
                    <!-- signup Button -->
                    <button type="submit" class="btn btn-success btn-block bb-form__btn" id="signup__submit">
                      Signup
                    </button>
<!--                    <div class="form__alert alert alert-danger mt-3 fz-16 text-center" style="display:none;" role="alert">-->
<!--                       This account already exists,please login-->
<!--                      </div>-->
                  </form>
                  <!-- Registration Message -->

                  <p class="mt-3 text-center fz-16">
                    Already have an account? <a href="{% url 'backend:login' %}" class="bb-form__switcher">Login here</a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Add Bootstrap JS and jQuery -->
<!--    <script src="../Assets/includes/js/jquery.js"></script>-->
    <!-- custom script here -->
<!--    <script src="../Assets/includes/js/formscript.js"></script>-->
  </body>
</html>